-- Active: 1671141046592@@127.0.0.1@3306@star_travel

INSERT INTO COUNTRY VALUES (NULL, 'Brasil', "América do Sul", 1, 5, "BRL");

INSERT INTO USER_PROFILE(USERNAME, EMAIL, PASSWORDS, NICKNAME, FK_COUNTRY) VALUES('Ivan Freire', 'ivan@gmmail.com', '321318', 'Lullyfitf', 1);
INSERT INTO USER_PROFILE(USERNAME, EMAIL, PASSWORDS, NICKNAME, FK_COUNTRY) VALUES('Ivan Freire', 'ivan@oputlil.com', '421421678', 'Lullyfite', 1);
INSERT INTO USER_PROFILE(USERNAME, EMAIL, PASSWORDS, NICKNAME, FK_COUNTRY) VALUES('Ivan Freire', 'ivan@gfwel.com', '42142178', 'Lullyfita', 1);
-- UPDATE user_profile
-- SET BIO = 'Sou feliz', FK_STATE = 100
-- WHERE ID = 2210;

INSERT INTO POST (FK_USER, POST_CONTENT, FK_COUNTRY, POST_TIME) VALUES (2210, 'Aconteceu algo chato', 1, NOW());

INSERT INTO POST_COMMENTS(COMMENT_CONTENT, FK_POST, FK_USER, COMMENT_TIME) VALUES ('FEFEF', 9900, 2212, NOW());

INSERT INTO LIKES (FK_POST, FK_USER) VALUES (9900,2212);




